name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: test the envs
      run: echo "Hello $MESSAGE "
      env:
        MESSAGE: ${{ Secrets.USERNAME }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -o dist
      
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2.3.0
      with:
        name: AppPackage
        path: dist/**

   
